# Generated by Django 5.2.11 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_marks_unique_together_marks_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
