# Generated by Django 5.2.11 on 2026-03-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='endsem',
            new_name='ese',
        ),
        migrations.AddField(
            model_name='marks',
            name='grade_points',
            field=models.IntegerField(default=0),
        ),
    ]
