# Generated by Django 5.2.11 on 2026-03-28 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_marks_ese_alter_marks_midsem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='ese',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
