# Generated by Django 5.2.11 on 2026-03-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_marks_ese'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed')], default='registered', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=500)),
                ('result_marks', models.IntegerField(blank=True, null=True)),
                ('result_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('result_grade_points', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'subject', 'attempt_number')},
            },
        ),
    ]
