# Generated by Django 5.2.11 on 2026-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline (Bank Challan)'), ('pending', 'Payment Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='backlog',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='backlog_receipts/'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered (Payment Pending)'), ('payment_verified', 'Payment Verified'), ('approved', 'Approved for Exam'), ('completed', 'Exam Completed'), ('passed', 'Passed'), ('failed', 'Failed')], default='registered', max_length=20),
        ),
    ]
