# Generated by Django 5.2.11 on 2026-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_backlog_payment_method_backlog_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
    ]
