# Generated by Django 5.2.11 on 2026-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_marks_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
